### ISSUE TITLE
Registration process

### ISSUE THREAD

**Issue by josephmtinangi** [zechtz/tigoPesa#1]
Have you tried to use this API. In the Integration steps they have said that one should Register with Millicom Tigo. When I visit Millicom website I don't see any place that register. 

If you have already tried this API please give me the proper steps.

**Comment by Olaw2jr** [comment]
I have not used it, but i think using it you have to check with the offices

**Comment by alfredmack** [comment]
Am out of the country, any idea/alternative way of getting registered??
