### ISSUE TITLE
Update the docs

### ISSUE THREAD

**Issue by alphaolomi** [zechtz/tigoPesa#2]
- Update to latest mkdocs 
- Visual UI/display of docs ie. use another theme eg lumen from 
- Add and use  `requirements.txt` from  dependency management 
- Update wording here and there

**Comment by alphaolomi** [comment]
@zechtz

**Comment by zechtz** [comment]
> @zechtz

**Comment by alphaolomi** [comment]
Thanks @zechtz for the feedback

I don't mind at all, transfer to @alphaolomi,

**Comment by zechtz** [comment]
> Thanks @zechtz for the feedback
> 
> I don't mind at all, transfer to @alphaolomi,

It says you already have the repo

**Comment by alphaolomi** [comment]
> > Thanks @zechtz for the feedback
> > I don't mind at all, transfer to @alphaolomi,
> 
> It says you already have the repo

Sorry try again, I had a forked, i removed it,  hope it works now

**Comment by alphaolomi** [comment]
Done ✅ 

Also I sent an email to your gmail
